"""Initial database schema - Phase 6

Revision ID: 433d6fa5c900
Revises: 
Create Date: 2025-11-13 15:54:23.129564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433d6fa5c900'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_concepts', sa.JSON(), nullable=False),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cluster_skill_level', 'clusters', ['skill_level'], unique=False)
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vector_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tfidf_vector', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_documents_doc_id'), 'vector_documents', ['doc_id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=50), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.Column('content_length', sa.Integer(), nullable=True),
    sa.Column('skill_level', sa.String(length=50), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_ingested', 'documents', ['ingested_at'], unique=False)
    op.create_index('idx_doc_owner_cluster', 'documents', ['owner_username', 'cluster_id'], unique=False)
    op.create_index('idx_doc_source_skill', 'documents', ['source_type', 'skill_level'], unique=False)
    op.create_index(op.f('ix_documents_cluster_id'), 'documents', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_documents_doc_id'), 'documents', ['doc_id'], unique=True)
    op.create_index(op.f('ix_documents_ingested_at'), 'documents', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_documents_owner_username'), 'documents', ['owner_username'], unique=False)
    op.create_index(op.f('ix_documents_skill_level'), 'documents', ['skill_level'], unique=False)
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_concept_confidence', 'concepts', ['confidence'], unique=False)
    op.create_index('idx_concept_name_category', 'concepts', ['name', 'category'], unique=False)
    op.create_index(op.f('ix_concepts_category'), 'concepts', ['category'], unique=False)
    op.create_index(op.f('ix_concepts_document_id'), 'concepts', ['document_id'], unique=False)
    op.create_index(op.f('ix_concepts_name'), 'concepts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concepts_name'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_document_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_category'), table_name='concepts')
    op.drop_index('idx_concept_name_category', table_name='concepts')
    op.drop_index('idx_concept_confidence', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_skill_level'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_username'), table_name='documents')
    op.drop_index(op.f('ix_documents_ingested_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_cluster_id'), table_name='documents')
    op.drop_index('idx_doc_source_skill', table_name='documents')
    op.drop_index('idx_doc_owner_cluster', table_name='documents')
    op.drop_index('idx_doc_ingested', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_vector_documents_doc_id'), table_name='vector_documents')
    op.drop_table('vector_documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_index('idx_cluster_skill_level', table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
