"""Add YouTube metadata fields to documents

Revision ID: c3dc67ca08ff
Revises: hier_001
Create Date: 2025-11-22 15:26:34.147836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3dc67ca08ff'
down_revision: Union[str, Sequence[str], None] = 'hier_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('video_title', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('video_creator', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('video_type', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('target_audience', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('key_takeaways', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('estimated_watch_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'estimated_watch_time')
    op.drop_column('documents', 'key_takeaways')
    op.drop_column('documents', 'target_audience')
    op.drop_column('documents', 'video_type')
    op.drop_column('documents', 'video_creator')
    op.drop_column('documents', 'video_title')
    # ### end Alembic commands ###
